### ISSUE TITLE
Doesn't install on io.js

### ISSUE THREAD

**Issue by mzgol** [node-inspector/v8-debug#10]
The package doesn't install on io.js. That also makes node-inspector not io.js-compatible.

```
$ node --version
v1.1.0
$ npm --version
2.5.0
$ npm i v8-debug
-
> v8-debug@0.3.4 install /Users/mgol/_/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:193:25: warning: ISO C++11 does not allow conversion from string literal to 'char *'
      [-Wc++11-compat-deprecated-writable-strings]
          result_type = "";
                        ^
../src/debug.cc:197:46: warning: result of comparison against a string literal is unspecified (use strncmp instead)
      [-Wstring-compare]
        if (!result.IsEmpty() && result_type == "Object") {
                                             ^  ~~~~~~~~
../src/debug.cc:208:27: warning: result of comparison against a string literal is unspecified (use strncmp instead)
      [-Wstring-compare]
          if (result_type == "Object" && object->IsFunction())
                          ^  ~~~~~~~~
In file included from ../src/debug.cc:2:
In file included from ../node_modules/nan/nan.h:74:
../node_modules/nan/nan_new.h:200:10: error: call to 'New' is ambiguous
  return NanIntern::Factory<T>::New(arg0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/debug.cc:67:63: note: in instantiation of function template specialization 'NanNew<v8::Integer, long long>' requested here
        exceptionDetails->Set(NanNew<v8::String>("scriptId"), NanNew<v8::Integer>(message->GetScriptOrigin().ScriptID()->Value()));
                                                              ^
../node_modules/nan/nan_new.h:100:26: note: candidate function
  static inline return_t New(int32_t value);
                         ^
../node_modules/nan/nan_new.h:101:26: note: candidate function
  static inline return_t New(uint32_t value);
                         ^
3 warnings and 1 error generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mgol/.nvm/versions/io.js/v1.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1040:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/Users/mgol/.nvm/versions/io.js/v1.1.0/bin/iojs" "/Users/mgol/.nvm/versions/io.js/v1.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=v8-debug" "--configuration=Release" "--module_name=debug" "--version=0.3.4" "--minor=3" "--patch=4" "--runtime=node" "--node_abi=node-v43" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=v8-debug" "--host=https://node-inspector.s3.amazonaws.com/" "--module_path=/Users/mgol/_/node_modules/v8-debug/build/debug/v0.3.4/node-v43-darwin-x64" "--module=/Users/mgol/_/node_modules/v8-debug/build/debug/v0.3.4/node-v43-darwin-x64/debug.node" "--remote_path=./debug/v0.3.4/" "--package_name=node-v43-darwin-x64.tar.gz" "--staged_tarball=build/stage/debug/v0.3.4/node-v43-darwin-x64.tar.gz" "--hosted_path=https://node-inspector.s3.amazonaws.com/debug/v0.3.4/" "--hosted_tarball=https://node-inspector.s3.amazonaws.com/debug/v0.3.4/node-v43-darwin-x64.tar.gz"
gyp ERR! cwd /Users/mgol/_/node_modules/v8-debug
gyp ERR! node -v v1.1.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/mgol/.nvm/versions/io.js/v1.1.0/bin/iojs /Users/mgol/.nvm/versions/io.js/v1.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=v8-debug --configuration=Release --module_name=debug --version=0.3.4 --minor=3 --patch=4 --runtime=node --node_abi=node-v43 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=v8-debug --host=https://node-inspector.s3.amazonaws.com/ --module_path=/Users/mgol/_/node_modules/v8-debug/build/debug/v0.3.4/node-v43-darwin-x64 --module=/Users/mgol/_/node_modules/v8-debug/build/debug/v0.3.4/node-v43-darwin-x64/debug.node --remote_path=./debug/v0.3.4/ --package_name=node-v43-darwin-x64.tar.gz --staged_tarball=build/stage/debug/v0.3.4/node-v43-darwin-x64.tar.gz --hosted_path=https://node-inspector.s3.amazonaws.com/debug/v0.3.4/ --hosted_tarball=https://node-inspector.s3.amazonaws.com/debug/v0.3.4/node-v43-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mgol/_/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:981:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1053:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Users/mgol/_/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mgol/_/node_modules/v8-debug
node-pre-gyp ERR! node -v v1.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/Users/mgol/.nvm/versions/io.js/v1.1.0/bin/iojs /Users/mgol/.nvm/versions/io.js/v1.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=v8-debug --configuration=Release --module_name=debug --version=0.3.4 --minor=3 --patch=4 --runtime=node --node_abi=node-v43 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=v8-debug --host=https://node-inspector.s3.amazonaws.com/ --module_path=/Users/mgol/_/node_modules/v8-debug/build/debug/v0.3.4/node-v43-darwin-x64 --module=/Users/mgol/_/node_modules/v8-debug/build/debug/v0.3.4/node-v43-darwin-x64/debug.node --remote_path=./debug/v0.3.4/ --package_name=node-v43-darwin-x64.tar.gz --staged_tarball=build/stage/debug/v0.3.4/node-v43-darwin-x64.tar.gz --hosted_path=https://node-inspector.s3.amazonaws.com/debug/v0.3.4/ --hosted_tarball=https://node-inspector.s3.amazonaws.com/debug/v0.3.4/node-v43-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/Users/mgol/.nvm/versions/io.js/v1.1.0/bin/npm" "i" "v8-debug"
npm ERR! node v1.1.0
npm ERR! npm  v2.5.0
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.3.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.3.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mgol/_/npm-debug.log
```

**Comment by hkskoglund** [comment]
I just tried to install node-inspector on iojs and got 

<code>In file included from ../node_modules/nan/nan.h:74:0,
                 from ../src/debug.cc:2:
../node_modules/nan/nan_new.h: In instantiation of ‘typename NanIntern::Factory<T>::return_t NanNew(A0) [with T = v8::Integer; A0 = long int; typename NanIntern::Factory<T>::return_t = v8::Local<v8::Integer>]’:
../src/debug.cc:67:129:   required from here
../node_modules/nan/nan_new.h:200:41: error: call of overloaded ‘New(long int&)’ is ambiguous
   return NanIntern::Factory<T>::New(arg0);
</code>

**Comment by mzgol** [comment]
This is not relevant anymore, io.js is dead.
