### ISSUE TITLE
iojs 2.0.0 requires new prebuilt packages

### ISSUE THREAD

**Issue by mrgamer** [node-inspector/v8-debug#13]
On windows x64 it does not download a prebuild tarball and so fails in installing
I know it's natural, just opening the issue to keep track of progress.

npm log:
```
$ npm install -g v8-debug
\
> v8-debug@0.4.3 install C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build


C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug>node "c:\Users\valerio\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean

C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug>node "c:\Users\valerio\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug\build\debug\v0.4.3\node-v44-win32-x64\debug.node --module_name=debug --module_path=C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug\build\debug\v0.4.3\node-v44-win32-x64 --python=C:Python27
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (c:\Users\valerio\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (c:\Users\valerio\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:414:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:304:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "c:\\Program Files\\iojs\\node.exe" "c:\\Users\\valerio\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\valerio\\AppData\\Roaming\\npm\\node_modules\\v8-debug\\build\\debug\\v0.4.3\\node-v44-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\valerio\\AppData\\Roaming\\npm\\node_modules\\v8-debug\\build\\debug\\v0.4.3\\node-v44-win32-x64" "--python=C:Python27"
gyp ERR! cwd C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug
gyp ERR! node -v v2.0.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug\build\debug\v0.4.3\node-v44-win32-x64\debug.node --module_name=debug --module_path=C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug\build\debug\v0.4.3\node-v44-win32-x64 --python=C:Python27' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:953:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "c:\\Program Files\\iojs\\node.exe" "C:\\Users\\valerio\\AppData\\Roaming\\npm\\node_modules\\v8-debug\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug
node-pre-gyp ERR! node -v v2.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.5
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug\build\debug\v0.4.3\node-v44-win32-x64\debug.node --module_name=debug --module_path=C:\Users\valerio\AppData\Roaming\npm\node_modules\v8-debug\build\debug\v0.4.3\node-v44-win32-x64 --python=C:Python27' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\iojs\\node.exe" "c:\\USERS\\VALERIO\\APPDATA\\ROAMING\\NPM\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "v8-debug"
npm ERR! node v2.0.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\valerio\npm-debug.logù
```

**Comment by mrgamer** [comment]
Closing because this kind of issues does not seem to be tracked.
Eventually I will just contribute a prebuilt package instead of opening issues regarding the lack of thereof. :+1:

**Comment by 3y3** [comment]
This issue was fixed some time ago.
You can try to reinstall v8-debug now.
