### ISSUE TITLE
Error running yeoman angular-fullstack generator

### ISSUE THREAD

**Issue by tribet84** [node-inspector/v8-debug#17]
I'm having the following issue and it points to the v8-debug repository:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\src\tests\node\yeo2\npm-debug.log

I can't post the entire file either attach it here but I spot this within the npm-debug.log file:

386 warn install Couldn't install optional dependency: Unsupported
387 verbose install Error: Unsupported
387 verbose install     at checkPlatform (C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\index.js:46:14)
387 verbose install     at Array.<anonymous> (C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
387 verbose install     at LOOP (C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
387 verbose install     at C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
387 verbose install     at checkEngine (C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\index.js:25:10)
387 verbose install     at Array.<anonymous> (C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
387 verbose install     at LOOP (C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
387 verbose install     at chain (C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
387 verbose install     at module.exports.isInstallable (C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:26:3)
387 verbose install     at resolveWithNewModule (C:\Users\user.user\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:413:12)

**Comment by meezyart** [comment]
This is happening for me to

**Comment by tribet84** [comment]
I still didn't solve it...

**Comment by meezyart** [comment]
figured it out if 
https://github.com/DaftMonk/generator-angular-fullstack/issues/1416

update the package.json
with the new node inspector version

**Comment by limitedaccess** [comment]
issue solved with the suggestion above.
