### ISSUE TITLE
failure to install v8-debug

### ISSUE THREAD

**Issue by pei-han** [node-inspector/v8-debug#26]
First of all,i install node-inspector by command "npm install -g node-inpsector --unsafe-perm" on Ubuntu 14.04LTS 32bit,and then it is successful.

Then i access http://127.0.0.1:8080/?port=5858,show "Can not find module $NPM_HOME/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.3/node-v47-linux-ia32/debug.node"on the console.

Below is error info on the period of installation
@3y3 can you help me? thanks so much.
npm install -g v8-debug
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/node-v5.6.0-linux-x86/bin/npm" "install" "v8-debug"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/npm-global/lib/node_modules/node-inspector/npm-debug.log
root@ubuntu:/usr/npm-global/lib/node_modules/node-inspector# npm install v8-debug -g
npm WARN lifecycle v8-debug@0.7.3~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.3 node -e 'process.exit(0)' /usr/npm-global/lib/node_modules/.staging/v8-debug-858816f5

> v8-debug@0.7.3 install /usr/npm-global/lib/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/npm-global/lib/node_modules/v8-debug/.node-gyp"
make: Entering directory `/usr/npm-global/lib/node_modules/v8-debug/build'
make: *** No rule to make target `../.node-gyp/5.6.0/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/usr/npm-global/lib/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/npm-global/lib/node_modules/v8-debug/build/debug/v0.7.3/node-v47-linux-ia32/debug.node" "--module_name=debug" "--module_path=/usr/npm-global/lib/node_modules/v8-debug/build/debug/v0.7.3/node-v47-linux-ia32"
gyp ERR! cwd /usr/npm-global/lib/node_modules/v8-debug
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/node-v5.6.0-linux-x86/bin/node /usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/npm-global/lib/node_modules/v8-debug/build/debug/v0.7.3/node-v47-linux-ia32/debug.node --module_name=debug --module_path=/usr/npm-global/lib/node_modules/v8-debug/build/debug/v0.7.3/node-v47-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/npm-global/lib/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.19.0-25-generic
node-pre-gyp ERR! command "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/npm-global/lib/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/npm-global/lib/node_modules/v8-debug
node-pre-gyp ERR! node -v v5.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.27
node-pre-gyp ERR! not ok 
Failed to execute '/usr/node-v5.6.0-linux-x86/bin/node /usr/node-v5.6.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/npm-global/lib/node_modules/v8-debug/build/debug/v0.7.3/node-v47-linux-ia32/debug.node --module_name=debug --module_path=/usr/npm-global/lib/node_modules/v8-debug/build/debug/v0.7.3/node-v47-linux-ia32' (1)
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/node-v5.6.0-linux-x86/bin/node" "/usr/node-v5.6.0-linux-x86/bin/npm" "install" "v8-debug" "-g"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/npm-global/lib/node_modules/node-inspector/npm-debug.log
root@ubuntu:/usr/npm-global/lib/node_modules/node-inspector# node-inspector
Node Inspector v0.12.8
Visit http://127.0.0.1:8080/?port=5858 to start debugging.

**Comment by dimircin** [comment]
i have the same issue. Any ideas to fix?

**Comment by 3y3** [comment]
Hm. I see that you use ia32 linux architecture. Unfortunately we don't have prebuilt binaries for ia32 on linux. In this situation node-gyp tries to compile binary for you.
Maybe you don't have required dependencies for build. For linux I use `gcc` v4.7.2

**Comment by larrybotha** [comment]
Getting this on Mac OSX 10.8
v0.12.6-8
Node 5.10.1

**Comment by vijraman** [comment]
Having install issue on Mac OSX 10.9.5
npm ERR! v8-debug@0.7.7 preinstall: `node -e 'process.exit(0)'`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 preinstall script 'node -e 'process.exit(0)''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.

node -v 
v6.1.0
npm --ve
3.8.6

**Comment by vinniefm** [comment]
Install issues on OSX 10.11.4

npm ERR! v8-debug@0.7.7 preinstall: `node -e 'process.exit(0)'`
npm ERR! spawn sh ENOENT
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 preinstall script 'node -e 'process.exit(0)''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.

node -v
6.0.0
npm -v
3.8.6

**Comment by alanmimms** [comment]
Same on Ubuntu 16.04 using node v6.1.0 installed via nvm if it isn't obvious from the below (it is).

```
$ npm install -g node-inspector

> v8-profiler@5.6.3 preinstall /home/alan/.nvm/versions/node/v6.1.0/lib/node_modules/.staging/v8-profiler-7890d715
> npm install node-pre-gyp

/home/alan/.nvm/versions/node/v6.1.0/bin/node-pre-gyp -> /home/alan/.nvm/versions/node/v6.1.0/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
/home/alan/.nvm/versions/node/v6.1.0/lib
└── node-pre-gyp@0.6.28 


> v8-debug@0.7.7 preinstall /home/alan/.nvm/versions/node/v6.1.0/lib/node_modules/.staging/v8-debug-b0ae679d
> node -e 'process.exit(0)'

/home/alan/.nvm/versions/node/v6.1.0/lib
└── (empty)

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/alan/.nvm/versions/node/v6.1.0/bin/node" "/home/alan/.nvm/versions/node/v6.1.0/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh

npm ERR! v8-debug@0.7.7 preinstall: `node -e 'process.exit(0)'`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 preinstall script 'node -e 'process.exit(0)''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e 'process.exit(0)'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alan/longhorn/npm-debug.log
npm ERR! code 1

```

**Comment by goldnmean** [comment]
Install issues on OSX 10.11.3
node -v 6.1.0
npm -v  3.8.6

```
npm ERR! v8-debug@0.7.7 preinstall: `node -e 'process.exit(0)'`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 preinstall script 'node -e 'process.exit(0)''.
```

**Comment by awolski** [comment]
Getting the same issue since 0.7.7. Error occurs installing node-inspector which uses 

`"v8-debug": "~0.7.1",`

Environment is centos:6.6 (docker image):

```
> v8-profiler@5.6.3 preinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
> npm install node-pre-gyp
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-pre-gyp"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! path /root/.npm/node-pre-gyp
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! Error: EACCES, mkdir '/root/.npm/node-pre-gyp'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/root/.npm/node-pre-gyp'] errno: -13, code: 'EACCES', path: '/root/.npm/node-pre-gyp' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler/npm-debug.log
> v8-debug@0.7.7 preinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'
> v8-debug@0.7.7 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build
[v8-debug] Success: "/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v14-linux-x64/debug.node" is installed via remote
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-inspector" "rtail"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! v8-profiler@5.6.3 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the v8-profiler@5.6.3 preinstall script 'npm install node-pre-gyp'.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install node-pre-gyp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

**Comment by smanos** [comment]
Getting it too on:

npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
```

`
> v8-debug@0.7.7 preinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
 
> v8-profiler@5.6.5 preinstall /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
-
> v8-debug@0.7.7 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-pre-gyp: command not found

> v8-profiler@5.6.5 install /usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-pre-gyp: command not found
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.
```

**Comment by steventj** [comment]
Got the same issue here.

```
npm ERR! node v4.4.7
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output `above.
```

**Comment by bhoomit** [comment]
did anyone find any solution to this?

**Comment by sqren** [comment]
Possible related to https://github.com/node-inspector/v8-debug/issues/31

I've created a repo to make it easier for the maintainers to reproduce the issue I'm seeing: https://github.com/sqren/v8-debug-debug

**Comment by mcnelson** [comment]
Same problem on Fedora 24.

**Comment by ulrichnzuzi** [comment]
see russfrisch solution at https://github.com/node-inspector/v8-debug/issues/7

**Comment by csvan** [comment]
Reproducible on Windows 7 Enterprise

**Comment by dracudakid** [comment]
Same problem on MAC OS 10.11.4
node v7.0.0
npm 3.10.8

**Comment by r3dcrosse** [comment]
Same problem on MAC OS 10.11.6

`npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-inspector"
npm ERR! node v7.0.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.`

**Comment by MPX4132** [comment]
Same on macOS 10.12.1.
node v7.2.0 & v6.9.1.
npm v4.0.3 & the one bundled with node v6.9.1.

**Comment by yunghoy** [comment]
* working correctly with Node 6.x version

npm ERR! node v7.3.0
npm ERR! npm  v3.10.10

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/be/npm-debug.log
The command '/bin/sh -c npm install /app/be/' returned a non-zero code: 1
error with docker

**Comment by shauntrick** [comment]
Any solution yet ?

**Comment by stenio123** [comment]
Looks like node-inspector doesnt work with latest node versions, per https://github.com/node-inspector/node-inspector/issues/907

However you might not need it, similar functionality is now built into node. Just use node --inspect yourApp.js and follow similar workflow.

**Comment by matthewepler** [comment]
Works with Node v6.9.4. If you've never installed another version of Node alongside your existing one, I recommend using nvm.  [Here's ](https://nodecasts.io/update-node-js/)a good quick intro.

**Comment by jwnx** [comment]
@matthewepler Thank you very much, 6.3.1 works like a charm. Was using 7.4.0.

**Comment by waltonryan** [comment]
@matthewepler Thanks, I was able to use node `v6.5.0` with our heroku build process.

```
/ package.json
...
  "engines": {
    "node": "~6.5.0",
    "npm": "3.10.7"
  },
...
```

**Comment by Shane-Walsh** [comment]
Delete "grunt-node-inspector" from package.json

Heroku does not like grunt-node-inspector with node v7.1.0

**Comment by khaledalyawad** [comment]
try `npm rebuild node-sass`

**Comment by hoogw** [comment]
I have same issue with node -v 9.6

I solve my problem by install  nvm-windows to use node 5.6.0,

node after 6.3 will conflict with grunt-node-inspector, because node after 6.3 will have its own debugger.

So you have to use node <6,  v5.6.0 is good enough

nvm-windows let you run multiple node version at same time, I use it to go back v5.6.0

**Comment by yuukiii** [comment]
I solved it by using node 6.11

**Comment by ruzpuz** [comment]
Guys is there a workaround to not downgrade to node <= 10?

**Comment by migueloop** [comment]
I just updated node inspector to the last version to dix my issue. You can do this or downgrade node to v.6

**Comment by ranupoju0126** [comment]
![image](https://user-images.githubusercontent.com/33760139/45183329-c8450000-b1f1-11e8-8eba-51e33317ec11.png)

I got this error message while running grunt serve, after upgrading nodev6 to nodev8

then, I replace the string debug with inspect in my gruntfile.js, then it worked like charm.

NodeV8 simply says to use -inspect instead of debug

![image](https://user-images.githubusercontent.com/33760139/45183482-38ec1c80-b1f2-11e8-8a70-98592d0623aa.png)
