### ISSUE TITLE
node-pre-gyp install --fallback-to-build 

### ISSUE THREAD

**Issue by krushnachandra** [node-inspector/v8-debug#28]
> node-zopfli@1.4.0 install E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.4.7 (node-v46 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Krushna\\Angular2\\AdminTemplate\\ng2-admin\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\Krushna\\Angular2\\AdminTemplate\\ng2-admin\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=E:\\Krushna\\Angular2\\AdminTemplate\\ng2-admin\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-zopfli
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Krushna\\Angular2\\AdminTemplate\\ng2-admin\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-zopfli
node-pre-gyp ERR! node -v v4.4.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
ng2-admin@0.0.1 E:\Krushna\Angular2\AdminTemplate\ng2-admin
+-- UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.1
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.1
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.1
+-- UNMET PEER DEPENDENCY @angular/forms@0.2.0
`-- ng2-bootstrap@1.0.22

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN enoent ENOENT: no such file or directory, open 'E:\Krushna\Angular2\AdminTemplate\ng2-admin\node_modules\Ionicons\package.json'
npm WARN ng2-bootstrap@1.0.22 requires a peer of @angular/common@2.0.0-rc.4 but none was installed.
npm WARN ng2-bootstrap@1.0.22 requires a peer of @angular/compiler@2.0.0-rc.4 but none was installed.
npm WARN ng2-bootstrap@1.0.22 requires a peer of @angular/core@2.0.0-rc.4 but none was installed.
npm WARN ng2-bootstrap@1.0.22 requires a peer of @angular/forms@0.2.0 but none was installed.

**Comment by AIon-Gbbe** [comment]
same here  - i tried to create a new angular 2 cli project - when i do ng init, after scaffolding it installs some dependencies, than fails, and throws this error. I can't even get a basic angular2 CLI project going. I updated angular-cli, node and npm today.  This happened after the update of the cli.
node is: v6.6.0 
npm is: 3.10.3. 
angular-cli is: 1.0.0-beta.14
os: win32 x64
Hmm.. any ideas?

**Comment by tomschreck** [comment]
I'm getting same issue as well.  Any updates?

**Comment by zerubeus** [comment]
+1

**Comment by detorresvc** [comment]
any update?

**Comment by shivarajnaidu** [comment]
Any Update >?????

**Comment by BaldwinLi** [comment]
Any Upate???
