### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by MankalMR** [node-inspector/v8-debug#30]
Executing 'yo meanjs' gives following error

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mmankala/Documents/MEANJS/mean/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)

[npm-debug.txt](https://github.com/node-inspector/v8-debug/files/379880/npm-debug.txt)

**Comment by areyoueye** [comment]
I get this same error on `npm install node-inspector`
> $ node -v
v7.0.0
$ npm -v
3.10.9

**Comment by interstellerS** [comment]
Same Error as @areyoueye with npm 3.10.8 .

**Comment by denmojo** [comment]
Same error with npm 3.10.3.

**Comment by kimbaudi** [comment]
Hmm...`yo meanjs` scaffolded a new meanjs project just fine for me. However, running `npm install` afterwards gave me the `node-pre-gyp install --fallback-to-build` error. I was able to resolve it by removing "node-inspection" dev dependency from `package.json` and running `npm install` again. I am using node v7.2.0 and npm v4.0.2. If you're running Node v6.3 or greater, that's all you need to do. Otherwise, you might need to use "node-gyp" (`npm install node-gyp -g`).

**Comment by piux** [comment]
@kimbaudi thanks, worked for me im using windows 8.8 and node 7.10

**Comment by DarkBitz** [comment]
My workaround:
npm install node-gyp -g
npm install --production
npm install
