### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by cy2003** [node-inspector/v8-debug#37]
Hi,

I'm getting this message on my terminal to let you know that this fails on my system. 

And to include this file. 

/Users/cathyyee/Labs/react-create-element-lab-web-1116/npm-debug.log

Thank you.

Cathy

**Comment by orangebook** [comment]
+1

**Comment by thomasshupeng** [comment]
+1, 

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
....

**Comment by robertBojor** [comment]
+1,

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-inspector" "-g"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.

**Comment by trojanliu** [comment]
trojan:uncentury trojan$ sudo npm install node-inspector -g
Password:
npm WARN lifecycle v8-debug@0.7.7~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/.staging/v8-debug-89dbfbca
npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/.staging/v8-profiler-64c78e35
/Users/trojan/.nvm/versions/node/v7.7.4/bin/node-inspector -> /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/node-inspector/bin/inspector.js
/Users/trojan/.nvm/versions/node/v7.7.4/bin/node-debug -> /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/node-inspector/bin/node-debug.js

> v8-debug@0.7.7 install /Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.4 (node-v51 ABI) (falling back to source compile with node-gyp) 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/trojan/.node-gyp/7.7.4/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/trojan/.node-gyp/7.7.4/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/trojan/.node-gyp/7.7.4/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/trojan/.node-gyp/7.7.4/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/trojan/.nvm/versions/node/v7.7.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0

**Comment by hustxiaoc** [comment]
@trojanliu , the latest version of `v8-debug` is `1.0.1` and  `1.0.0` of  `node-inspector`, please try again.

**Comment by unicorngoat** [comment]
Got the same error

node-pre-gyp install --fallback-to-build

/Users/Cody/hgcv1/npm-debug.log

Has anyone found a work around / fix?

**Comment by hustxiaoc** [comment]
@unicorngoat could you please post the error log here ? Thank you!
