### ISSUE TITLE
 node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by laguilerao** [node-inspector/v8-debug#41]
Hi, 

This is failing in my system:
 node-pre-gyp install --fallback-to-build

npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

[log.zip](https://github.com/node-inspector/v8-debug/files/972317/log.zip)

**Comment by hustxiaoc** [comment]
Hi, I didn't find any file in `log.zip`, have you missed something?

**Comment by laguilerao** [comment]
[log.zip](https://github.com/node-inspector/v8-debug/files/974059/log.zip)

Adding missing file.

**Comment by laguilerao** [comment]
[log.zip](https://github.com/node-inspector/v8-debug/files/974064/log.zip)

Attaching new zip file, previous one had the log deep in the directory hierarchy.

**Comment by hustxiaoc** [comment]
You are installing `v8-debug@0.7.7` which  doesn't work on node7.x , try `v8-debug@1.0.1` please.

**Comment by laguilerao** [comment]
Thanks!

**Comment by vipanwebdeveloper** [comment]
I am getting error 

could you please let me what can be solution.


Thanks,

[Uploading 2017-05-07T08_26_24_959Z-debug.txt…]()

**Comment by suni007** [comment]
I installed v8-debug@1.01 but it didn't worked and getting error
Linux 4.4.0-75-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.

**Comment by hustxiaoc** [comment]
@suni007 any more log?

**Comment by suni007** [comment]
Here is my log please check it.
[log.txt](https://github.com/node-inspector/v8-debug/files/1013090/log.txt)

.

**Comment by hustxiaoc** [comment]
```
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.8.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/suni/tellform/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::Call(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:38:27: error: no matching function for call to ‘v8::Debug::Call(v8::Local<v8::Function>&)’
         v8::Debug::Call(fn);
                           ^
In file included from ../src/debug.cc:1:0:
/home/suni/.node-gyp/7.8.0/include/node/v8-debug.h:198:28: note: candidate: static v8::MaybeLocal<v8::Value> v8::Debug::Call(v8::Local<v8::Context>, v8::Local<v8::Function>, v8::Local<v8::Value>)
   static MaybeLocal<Value> Call(Local<Context> context,
                            ^
/home/suni/.node-gyp/7.8.0/include/node/v8-debug.h:198:28: note:   candidate expects 3 arguments, 1 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::SendCommand(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:46:61: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                                             ^
In file included from ../src/debug.cc:1:0:
/home/suni/.node-gyp/7.8.0/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/suni/.node-gyp/7.8.0/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::RunScript(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:61:67: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Local<Context> debug_context = v8::Debug::GetDebugContext();
                                                                   ^
In file included from ../src/debug.cc:1:0:
/home/suni/.node-gyp/7.8.0/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/suni/.node-gyp/7.8.0/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc:66:54: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
           debug_context = v8::Debug::GetDebugContext();
                                                      ^
In file included from ../src/debug.cc:1:0:
/home/suni/.node-gyp/7.8.0/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/suni/.node-gyp/7.8.0/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
debug.target.mk:97: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: Leaving directory '/home/suni/tellform/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/suni/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-78-generic
gyp ERR! command "/usr/local/bin/node" "/home/suni/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/suni/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/suni/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64"
gyp ERR! cwd /home/suni/tellform/node_modules/v8-debug
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/suni/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/suni/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/suni/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/suni/tellform/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-78-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/suni/tellform/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/suni/tellform/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /home/suni/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/suni/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/suni/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
TellForm@2.0.0 /home/suni/tellform
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/suni/.npm/_logs/2017-05-19T03_58_31_260Z-debug.log
```

**Comment by hustxiaoc** [comment]
@suni007 , you are installing `v8-debug@0.7.7` which doesn't work on node7.8.0 , try `v8-debug@1.0.1` please.

**Comment by suni007** [comment]
I have tried by installed v8-debug@1.0.1 in my system but facing the same problem.

**Comment by hustxiaoc** [comment]
Same error log?

**Comment by suni007** [comment]
yeah getting same error log.

**Comment by diegosucaria** [comment]
Same error here, even if I install v8-debug@1.0.1 node-inspector is still trying with v0.7.7

**Comment by hustxiaoc** [comment]
@diegosucaria which version of Node Inspector  are you installing?

**Comment by dclarke-modus** [comment]
same issue here...this is frustrating. I log this on stackoverflow:

https://stackoverflow.com/questions/44472720/installing-node-inspector-through-vagrants-provision-file-issue

**Comment by mhornbacher** [comment]
Any updates? still broken here

**Comment by rustoceans** [comment]
please, any update?

**Comment by anand-neema** [comment]
Any Update getting the same error?

**Comment by cathect** [comment]
Same thing here

**Comment by gjdass** [comment]
Same. And I don't really have a choice of version, it's a sub-dependency of some package.

```
$ npm install

> v8-debug@0.7.7 preinstall E:\nodejs-blockchain\node_modules\v8-debug
> node -e 'process.exit(0)'


> v8-debug@0.7.7 install E:\nodejs-blockchain\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@9.4.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Python36\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\nodejs-blockchain\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v59-win32-x64\\debug.node" "--module_name=debug" "--module_path=E:\\nodejs-blockchain\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v59-win32-x64"
gyp ERR! cwd E:\nodejs-blockchain\node_modules\v8-debug
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\nodejs-blockchain\node_modules\v8-debug\build\debug\v0.7.7\node-v59-win32-x64\debug.node --module_name=debug --module_path=E:\nodejs-blockchain\node_modules\v8-debug\build\debug\v0.7.7\node-v59-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\nodejs-blockchain\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\nodejs-blockchain\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\nodejs-blockchain\node_modules\v8-debug
node-pre-gyp ERR! node -v v9.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\nodejs-blockchain\node_modules\v8-debug\build\debug\v0.7.7\node-v59-win32-x64\debug.node --module_name=debug --module_path=E:\nodejs-blockchain\node_modules\v8-debug\build\debug\v0.7.7\node-v59-win32-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

```
129 verbose stack Error: v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
129 verbose stack Exit status 1
129 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
129 verbose stack     at EventEmitter.emit (events.js:160:13)
129 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
129 verbose stack     at ChildProcess.emit (events.js:160:13)
129 verbose stack     at maybeClose (internal/child_process.js:943:16)
129 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

**Comment by FrenchNewbie** [comment]
hi i have a similar error when i try execute `npm install`  :+1: 

```
> uglifyjs-webpack-plugin@0.4.6 postinstall /root/hyphe/hyphe_frontend/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

module.js:540
    throw err;
    ^

Error: Cannot find module '/root/hyphe/hyphe_frontend/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/lib/post_install.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-01T09_20_00_126Z-debug.log
```
for information node v8.9.4 and npm v5.7.1

Thanks for ure help :)

**Comment by jobnte** [comment]
Any fix?

**Comment by xflihaibo** [comment]
lihaibo➜Desktop/github/nodetest» sudo npm install node-inspector -g                                                                                                    [17:34:08]
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated har-validator@4.2.1: this library is no longer supported

> v8-profiler@5.7.0 preinstall /Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'


> v8-debug@1.0.1 preinstall /Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'

/Users/lihaibo/.nvm/versions/node/v12.0.0/bin/node-inspector -> /Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/bin/inspector.js
/Users/lihaibo/.nvm/versions/node/v12.0.0/bin/node-debug -> /Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/bin/node-debug.js

> v8-debug@1.0.1 install /Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@12.0.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/lihaibo/.nvm/versions/node/v12.0.0/bin/node" "/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v72-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v72-darwin-x64"
gyp ERR! cwd /Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/lihaibo/.nvm/versions/node/v12.0.0/bin/node /Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v72-darwin-x64/debug.node --module_name=debug --module_path=/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v72-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
node-pre-gyp ERR! System Darwin 19.4.0
node-pre-gyp ERR! command "/Users/lihaibo/.nvm/versions/node/v12.0.0/bin/node" "/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v12.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/Users/lihaibo/.nvm/versions/node/v12.0.0/bin/node /Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v72-darwin-x64/debug.node --module_name=debug --module_path=/Users/lihaibo/.nvm/versions/node/v12.0.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v72-darwin-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lihaibo/.npm/_logs/2020-08-20T09_37_40_809Z-debug.log
