### ISSUE TITLE
ERROR yarn global add node-inspector 

### ISSUE THREAD

**Issue by tonychen0716** [node-inspector/v8-debug#44]
PS E:\> yarn global add node-inspector
yarn global v1.2.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠁ v8-debug: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\
[2/2] ⠁ v8-profiler: not ok
[-/2] ⠁ waiting...
[-/2] ⠁ waiting...
error C:\Users\TonyChen\AppData\Local\Yarn\config\global\node_modules\v8-debug: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\Users\TonyChen\AppData\Local\Yarn\config\global\node_modules\v8-debug
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.5.0 | win32 | x64
node-pre-gyp info check checked for "C:\Users\TonyChen\AppData\Local\Yarn\config\global\node_modules\v8-debug\build\debu
g\v1.0.1\node-v57-win32-x64\debug.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.
tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.5.0 (node-v57 ABI, unknown) (falling back t
o source compile with node-gyp)
node-pre-gyp http unable to verify the first certificate
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.5.0 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.5.0 | win32 | x64
gyp http GET https://nodejs.org/download/release/v8.5.0/node-v8.5.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1108:38)
gyp ERR! stack     at emitNone (events.js:105:13)
gyp ERR! stack     at TLSSocket.emit (events.js:207:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:638:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\TonyChen\\AppData\\Local\\Yarn\\config\\g
lobal\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v57-win32-x64\\debug.node" "--module_name=debug" "--module_pat
h=C:\\Users\\TonyChen\\AppData\\Local\\Yarn\\config\\global\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v57-win3
2-x64" "--msvs_version=2015"
gyp ERR! cwd C:\Users\TonyChen\AppData\Local\Yarn\config\global\node_modules\v8-debug
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\TonyChen\AppData\Local\Yarn\co
nfig\global\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node --module_name=debug --module_path=C:\
Users\TonyChen\AppData\Local\Yarn\config\global\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64 --msvs_versi
on=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\TonyChen\AppData\Local\Yarn\config\global\node_modules
\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TonyChen\\AppData\\Local\\Yarn\\config\\glob
al\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\TonyChen\AppData\Local\Yarn\config\global\node_modules\v8-debug
node-pre-gyp ERR! node -v v8.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\n

**Comment by tonychen0716** [comment]
https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz

``` xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>debug/v1.0.1/node-v57-win32-x64.tar.gz</Key>
<RequestId>7E611B147F6CD509</RequestId>
<HostId>
6UTxYh3dBNnNaEvqJNEl1zktys7TktKgpLNBK4Lvcwhaj9QvuAuNXBGjug0cLF0eDvzxo3cer3I=
</HostId>
</Error>
```
