### ISSUE TITLE
Firebase Module Installation Failled 

### ISSUE THREAD

**Issue by shamoorpanik1** [node-inspector/v8-debug#45]
Node Version- v 9.5.0
npm - v5.6.0
Can you please help me out to resolve this issue. 
This is the output of the terminal.
C:\Windows\system32>npm install -g firebase

> grpc@1.9.1 install C:\Users\PankajKapoor\AppData\Roaming\npm\node_modules\fire
base\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/g
rpc-precompiled-binaries/node/grpc/v1.9.1/node-v59-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@9.5.0 (no
de-v59 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the
PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--library=static_library" "--module=C:\\Users\\PankajKapoor\\
AppData\\Roaming\\npm\\node_modules\\firebase\\node_modules\\grpc\\src\\node\\ex
tension_binary\\node-v59-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_
node" "--module_path=C:\\Users\\PankajKapoor\\AppData\\Roaming\\npm\\node_module
s\\firebase\\node_modules\\grpc\\src\\node\\extension_binary\\node-v59-win32-x64
-unknown" "--python=python2.7"
gyp ERR! cwd C:\Users\PankajKapoor\AppData\Roaming\npm\node_modules\firebase\nod
e_modules\grpc
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s configure --fallback-to-build --library=static_library --module=C:\Users\Panka
jKapoor\AppData\Roaming\npm\node_modules\firebase\node_modules\grpc\src\node\ext
ension_binary\node-v59-win32-x64-unknown\grpc_node.node --module_name=grpc_node
--module_path=C:\Users\PankajKapoor\AppData\Roaming\npm\node_modules\firebase\no
de_modules\grpc\src\node\extension_binary\node-v59-win32-x64-unknown --python=py
thon2.7' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\PankajKapoor\A
ppData\Roaming\npm\node_modules\firebase\node_modules\grpc\node_modules\node-pre
-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pank
ajKapoor\\AppData\\Roaming\\npm\\node_modules\\firebase\\node_modules\\grpc\\nod
e_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--l
ibrary=static_library"
node-pre-gyp ERR! cwd C:\Users\PankajKapoor\AppData\Roaming\npm\node_modules\fir
ebase\node_modules\grpc
node-pre-gyp ERR! node -v v9.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node
_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build
 --library=static_library --module=C:\Users\PankajKapoor\AppData\Roaming\npm\nod
e_modules\firebase\node_modules\grpc\src\node\extension_binary\node-v59-win32-x6
4-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\PankajKa
poor\AppData\Roaming\npm\node_modules\firebase\node_modules\grpc\src\node\extens
ion_binary\node-v59-win32-x64-unknown --python=python2.7' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.9.1 install: `node-pre-gyp install --fallback-to-build --library
=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PankajKapoor\AppData\Roaming\npm-cache\_logs\2018-02-19T15
_34_36_592Z-debug.log

C:\Windows\system32>

**Comment by Tom4U** [comment]
Did you already find a solution?!
