### ISSUE TITLE
v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by strawberry-code** [node-inspector/v8-debug#50]
I am trying to upgrade a NodeJS v6 project to use NodeJS v12.

After updating some packages, now I am stuck in this error.

I am using NodeJS v12.16.3 and npm 6.14.4.

```bash
npm install v8-debug
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> v8-debug@1.0.1 preinstall /media/psf/saServer2/node_modules/v8-debug
> node -e 'process.exit(0)'


> v8-debug@1.0.1 install /media/psf/saServer2/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v72-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v72-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/media/psf/saServer2/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
make: Entering directory '/media/psf/saServer2/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:1:10: fatal error: v8-debug.h: No such file or directory
 #include <v8-debug.h>
          ^~~~~~~~~~~~
compilation terminated.
debug.target.mk:114: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: Leaving directory '/media/psf/saServer2/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/parallels/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/home/parallels/.nvm/versions/node/v12.16.3/bin/node" "/home/parallels/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/media/psf/saServer2/node_modules/v8-debug/build/debug/v1.0.1/node-v72-linux-x64/debug.node" "--module_name=debug" "--module_path=/media/psf/saServer2/node_modules/v8-debug/build/debug/v1.0.1/node-v72-linux-x64"
gyp ERR! cwd /media/psf/saServer2/node_modules/v8-debug
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/parallels/.nvm/versions/node/v12.16.3/bin/node /home/parallels/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/media/psf/saServer2/node_modules/v8-debug/build/debug/v1.0.1/node-v72-linux-x64/debug.node --module_name=debug --module_path=/media/psf/saServer2/node_modules/v8-debug/build/debug/v1.0.1/node-v72-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/media/psf/saServer2/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.15.0-34-generic
node-pre-gyp ERR! command "/home/parallels/.nvm/versions/node/v12.16.3/bin/node" "/media/psf/saServer2/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /media/psf/saServer2/node_modules/v8-debug
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/home/parallels/.nvm/versions/node/v12.16.3/bin/node /home/parallels/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/media/psf/saServer2/node_modules/v8-debug/build/debug/v1.0.1/node-v72-linux-x64/debug.node --module_name=debug --module_path=/media/psf/saServer2/node_modules/v8-debug/build/debug/v1.0.1/node-v72-linux-x64' (1)
../src/debug.cc:1:10: fatal error: v8-debug.h: No such file or directory
 #include <v8-debug.h>
          ^~~~~~~~~~~~
compilation terminated.
debug.target.mk:114: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: Leaving directory '/media/psf/saServer2/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/parallels/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/home/parallels/.nvm/versions/node/v12.16.3/bin/node" "/home/parallels/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/media/psf/saServer2/node_modules/v8-debug/build/debug/v1.0.1/node-v72-linux-x64/debug.node" "--module_name=debug" "--module_path=/media/psf/saServer2/node_modules/v8-debug/build/debug/v1.0.1/node-v72-linux-x64"
gyp ERR! cwd /media/psf/saServer2/node_modules/v8-debug
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN awesome-typescript-loader@5.2.1 requires a peer of typescript@^2.7 || ^3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-harddisk-plugin@1.0.1 requires a peer of html-webpack-plugin@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN isparta-instrumenter-loader@1.0.1 requires a peer of webpack@^1.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/parallels/.npm/_logs/2020-05-08T14_58_19_741Z-debug.log
```

**Comment by jansc** [comment]
Did you ever find a solution for this issue? I'm having exactly the same problem during an upgrade from node 6 to 12.

**Comment by superlc** [comment]
I cannot install node-inspector successfully. I will show the log below
```
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security
patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated har-validator@4.2.1: this library is no longer supported

> v8-profiler@5.7.0 preinstall C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-profiler
> node -e 'process.exit(0)'


> v8-debug@1.0.1 preinstall C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
> node -e 'process.exit(0)'

C:\Program Files\nodejs\node-inspector -> C:\Program Files\nodejs\node_modules\node-inspector\bin\inspector.js
C:\Program Files\nodejs\node-debug -> C:\Program Files\nodejs\node_modules\node-inspector\bin\node-debug.js

> v8-debug@1.0.1 install C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@12.18.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@12.18.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
gypgyp ERR!  ERR!find VS
find VS
gyp gyp ERR! ERR!find VS  msvs_version not set from command line or npm config
find VSgyp msvs_version not set from command line or npm config
 gypERR!  ERR!find VS  VCINSTALLDIR not set, not running in VS Command Prompt
find VSgyp VCINSTALLDIR not set, not running in VS Command Prompt
 gypERR!  ERR!find VS  could not use PowerShell to find Visual Studio 2017 or newer
find VSgyp could not use PowerShell to find Visual Studio 2017 or newer
 gypERR!  ERR!find VS  looking for Visual Studio 2015
find VSgyp looking for Visual Studio 2015
 gypERR!  ERR!find VS  - not found
find VSgyp - not found
 gypERR!  ERR!find VS  not looking for VS2013 as it is only supported up to Node.js 8
find VSgyp not looking for VS2013 as it is only supported up to Node.js 8
 gypERR!  ERR!find VS
find VSgyp
 gypERR!  ERR!find VS **************************************************************
 gypfind VS  **************************************************************
ERR!gyp  find VSERR! You need to install the latest version of Visual Studio
 gypfind VS  You need to install the latest version of Visual Studio
ERR!gyp  find VSERR! including the "Desktop development with C++" workload.
 gypfind VS  including the "Desktop development with C++" workload.
ERR!gyp  find VSERR! For more information consult the documentation at:
 gypfind VS  For more information consult the documentation at:
ERR!gyp  find VSERR! https://github.com/nodejs/node-gyp#on-windows
 gypfind VS  https://github.com/nodejs/node-gyp#on-windows
ERR!gyp  find VSERR! **************************************************************
 gypfind VS  **************************************************************
ERR!gyp  find VSERR!
 find VS
gyp ERR! gypconfigure error 
ERR!gyp  configure errorERR! 
 gypstack  Error: Could not find any Visual Studio installation to use
ERR!gyp  stackERR! Error: Could not find any Visual Studio installation to use
 gypstack      at VisualStudioFinder.fail (C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
ERR!gyp  stackERR!     at VisualStudioFinder.fail (C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
 gypstack      at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
ERR!gyp  stackERR!     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
 gypstack      at VisualStudioFinder.findVisualStudio2013 (C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
ERR!gyp  stackERR!     at VisualStudioFinder.findVisualStudio2013 (C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
 gypstack      at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
ERR!gyp  stackERR!     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
 gypstack      at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
ERR!gyp  stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
ERR! gyp stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
ERR! gyp stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
ERR! gyp stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
ERR! gyp stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
ERR! gyp stack     at ChildProcess.exithandler (child_process.js:310:5)
ERR! gyp stack     at ChildProcess.exithandler (child_process.js:310:5)
ERR! gyp stack     at ChildProcess.emit (events.js:315:20)
ERR! gyp stack     at ChildProcess.emit (events.js:315:20)
ERR! gyp stack     at maybeClose (internal/child_process.js:1021:16)
ERR! stackgyp     at maybeClose (internal/child_process.js:1021:16)
 ERR!gyp  SystemERR! Windows_NT 6.1.7601
 gyp System Windows_NT 6.1.7601
ERR! gypcommand  "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chaoluo\\AppData\\Roaming\\nvm\\v12.18.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v72-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v72-win32-x64"
gypERR!  ERR!command  "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chaoluo\\AppData\\Roaming\\nvm\\v12.18.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v72-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v72-win32-x64"
cwd C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
gyp gyp ERR! ERR! cwd C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
node -v v12.18.0
gypgyp  ERR! ERR! node-gyp -v v5.1.0
node -v v12.18.0
gyp gypERR!  ERR!not ok
node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v72-win32-x64\debug.node --module_name=debug --module_path=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v72-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\node-inspector\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v12.18.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v72-win32-x64\debug.node --module_name=debug --module_path=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v72-win32-x64' (1)

> v8-profiler@5.7.0 install C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@12.18.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@12.18.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chaoluo\\AppData\\Roaming\\nvm\\v12.18.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.7.0\\node-v72-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.7.0\\node-v72-win32-x64"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-profiler
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v72-win32-x64\profiler.node --module_name=profiler --module_path=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v72-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\node-inspector\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-inspector\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-profiler
node-pre-gyp ERR! node -v v12.18.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\chaoluo\AppData\Roaming\nvm\v12.18.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v72-win32-x64\profiler.node --module_name=profiler --module_path=C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.7.0\node-v72-win32-x64' (1)
+ node-inspector@1.1.2
added 241 packages from 176 contributors in 35.54s
```
